name: Cut release

on:
  push:
    branches: [setup-jitpack]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up NPM 14
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
      # - name: Compile
      #   run: sbt compile
      # - name: Run tests
      #   run: sbt test
  release:
    needs: [tests]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
      - name: Create release tag file
        run: sbt createReleaseTag
      - name: Set release tag env variable
        run: cat tag.txt >> $GITHUB_ENV
      - name: Check tag
        run: echo "${{ env.RELEASE_TAG }}"
      - name: Create Draft Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          release_name: "SAP UI5 Laminar Bindings"
          draft: true
          prerelease: false
      - uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.create_release.outputs.id }}
